// Code generated by protoc-gen-go.
// source: image.proto
// DO NOT EDIT!

/*
Package caffe is a generated protocol buffer package.

It is generated from these files:
	image.proto

It has these top-level messages:
	Multi
*/
package caffe

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Multi struct {
	Width            *int32    `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height           *int32    `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	NumChannels      *int32    `protobuf:"varint,3,req,name=num_channels" json:"num_channels,omitempty"`
	XStride          *int32    `protobuf:"varint,9,req,name=x_stride" json:"x_stride,omitempty"`
	YStride          *int32    `protobuf:"varint,10,req,name=y_stride" json:"y_stride,omitempty"`
	ChannelStride    *int32    `protobuf:"varint,11,req,name=channel_stride" json:"channel_stride,omitempty"`
	Elem             []float64 `protobuf:"fixed64,12,rep,name=elem" json:"elem,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Multi) Reset()         { *m = Multi{} }
func (m *Multi) String() string { return proto.CompactTextString(m) }
func (*Multi) ProtoMessage()    {}

func (m *Multi) GetWidth() int32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Multi) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *Multi) GetNumChannels() int32 {
	if m != nil && m.NumChannels != nil {
		return *m.NumChannels
	}
	return 0
}

func (m *Multi) GetXStride() int32 {
	if m != nil && m.XStride != nil {
		return *m.XStride
	}
	return 0
}

func (m *Multi) GetYStride() int32 {
	if m != nil && m.YStride != nil {
		return *m.YStride
	}
	return 0
}

func (m *Multi) GetChannelStride() int32 {
	if m != nil && m.ChannelStride != nil {
		return *m.ChannelStride
	}
	return 0
}

func (m *Multi) GetElem() []float64 {
	if m != nil {
		return m.Elem
	}
	return nil
}

func init() {
}
